version: 2.1

orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    description: Runs unit tests and instrumented tests on the Android Common
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2024.01.1

    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew

      - android/create-avd:
          avd-name: avd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: avd
          no-window: true
          post-emulator-launch-assemble-command: ./gradlew assemble
      - android/run-tests:
          test-command: ./gradlew createSnapshotDebugUnitTestCoverageReport
      - android/run-tests:
          test-command: ./gradlew createSnapshotDebugAndroidTestCoverageReport
      - store_test_results:
          name: Store Unit Tests Results
          path: androidcommon_lib/build/test-results/testSnapshotDebugUnitTest
      - store_test_results:
          name: Store Android Tests Results
          path: androidcommon_lib/build/outputs/androidTest-results
      - store_artifacts:
          name: Store HTML Reports
          path: androidcommon_lib/build/reports

  build:
    docker:
      - image: cimg/android:2024.01
    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - run:
          name: Build Common
          command: ./gradlew assembleSnapshotDebug

  deploy:
    executor:
      name: android/android-docker
      tag: 2023.06.1
    steps:
      - checkout
      - run:
          name: Chmod Permissions
          command: sudo chmod +x gradlew
      - run:
          name: Publish library
          command: ./gradlew publishSnapshotDebugPublicationToODKXAndroidCommonRepository


  trigger-children:
    docker:
      - image: cimg/base:2024.01
    resource_class: small
    steps:
      - run:
          name: Trigger Survey pipelines
          command: |
            curl --location --request POST "https://circleci.com/api/v2/project/github/$CIRCLE_USERNAME/survey/pipeline" \
              --header 'Content-Type: application/json' \
              -u "${API_TOKEN}:" \
              --data "{\"branch\":\"$CIRCLE_BRANCH\"}" \
      - run:
          name: Trigger Tables pipeline
          command: |
            curl --location --request POST "https://circleci.com/api/v2/project/github/$CIRCLE_USERNAME/tables/pipeline" \
              --header 'Content-Type: application/json' \
              -u "${API_TOKEN}:" \
              --data "{\"branch\":\"$CIRCLE_BRANCH\"}" \


workflows:
  build-test-deploy-trigger-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
      - trigger-children:
          requires:
            - deploy